[package]
name = "metro-swc-transformer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

swc = "0.273.20"
swc_common = { version = "0.33.19", features = ["tty-emitter", "sourcemap"] }
swc_ecma_transforms_base = "0.137.15"
swc_ecma_visit = "0.98.6"
string_cache = "0.8.7"
js-sys = "0.3.69"
serde = "1.0.197"
serde-wasm-bindgen = "0.6.5"
swc_ecma_utils = "0.127.12"
serde_json = "1.0.114"


napi = "2.16.0"
napi-derive = "2.16.0"
es_resolve = "0.4.3"
threadpool = "1.8.1"

[build-dependencies]
napi-build = "2.1.2"
